# Generated by Django 5.1.3 on 2024-11-13 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('descripcion_equipo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('descripcion_proyecto', models.TextField()),
                ('fecha_inicio_proyecto', models.DateField(auto_now=True)),
                ('fecha_fin_proyecto', models.DateField()),
                ('estado_proyecto', models.CharField(max_length=50)),
                ('equipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.equipotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=100)),
                ('descripcion_rol', models.TextField()),
                ('equipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.equipotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sprint', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField(auto_now=True)),
                ('fecha_fin', models.DateField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=255)),
                ('descripcion_tarea', models.TextField()),
                ('fecha_inicio_tarea', models.DateField(auto_now=True)),
                ('fecha_fin_tarea', models.DateField()),
                ('estado_tarea', models.CharField(max_length=50)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='projects.sprint')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_comentario', models.TextField()),
                ('fecha_comentario', models.DateField(auto_now=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEquipo',
            fields=[
                ('usuario_equipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_union', models.DateField(auto_now=True)),
                ('rol_equipo', models.CharField(default='Owner', max_length=100)),
                ('es_creador', models.BooleanField(default=False)),
                ('equipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.equipotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario')),
            ],
        ),
    ]
