# Generated by Django 5.1.3 on 2024-11-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio_proyecto',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio_tarea',
            field=models.DateField(auto_now=True),
        ),
    ]
